Pantalla de inicio de sesión / registro
unahur-covid/frontend pull request #10
Opened 2021-01-20 03:02 UTC by JoaquinPettinari

Closes unahur-covid/planificacion#26

Falta mejorar un par de cosas

El branch quedó desactualizado con la rama master

2021-01-20 11:33 UTC, faloi requested changes
Todavía falta bastante laburo. Incluyan por favor una captura de pantalla de la UI.

2021-01-20 11:33 UTC, faloi commented on src/state/login.js
> +const informacionUsuarioState = atomFamily({
`atomFamily` se usa cuando querés tener varios átomos iguales. En este caso sería uno solo, va `atom`.

2021-01-20 11:33 UTC, faloi commented on src/components/registro/Registro.js
> +  const handleChange = (e) => {
Esta función se usa en varias vistas, podría ir a un archivo aparte y reutilizar.

2021-01-20 11:33 UTC, faloi commented on src/components/registro/Registro.js
> +    console.log(e.target.value);
Hay varios console.log, sacarlos

2021-01-20 11:33 UTC, faloi commented on src/components/registro/Registro.js
> +            <Grid item xs={6}>
Los campos no corresponden con su label. Y hay varios repetidos.

2021-01-20 11:33 UTC, faloi commented on src/components/login/Login.js
> +      setInfoUsuario(...values);
Lo que hay que guardar es la info que viene de la API y que incluye el token. Guardar los datos que ingresó el usuario no sirve de mucho.

2021-01-20 11:33 UTC, faloi commented on src/components/login/Login.js
> +      if (values.dni === '' || values.contrasenia === '') {
¿Hace falta manejarlo a mano esto? Me parece que con el `required` debería ser suficiente.

2021-01-20 11:33 UTC, faloi commented on src/App.js
> +            <Route path="/login">
La ruta de login debería ser la default.

2021-01-20 11:33 UTC, faloi commented on src/App.js
> +            <Route path="/login">
Además, hay que proteger las demás rutas para que no se puedan acceder sin estar logueado. Ver por ejemplo https://ui.dev/react-router-v5-protected-routes-authentication/.

2021-01-20 11:33 UTC, faloi commented on src/components/login/Login.js
> +      //create('/usuarios/login', ...values); CUANDO ANDE LA BD DESCOMENTAR
Y no se olviden del `await`.

2021-01-20 11:33 UTC, faloi commented on src/helpers/fetchApi.js
> +//Para login este no va muy bien, si en un futuro hay seguridad, como hacemos acá?
Hay que agregarle a todas las requests el header de autenticación, con el token que sale del átomo usuario.

2021-01-20 11:36 UTC, JoaquinPettinari commented on src/components/login/Login.js
> +      if (values.dni === '' || values.contrasenia === '') {
El require nos puso un * en el texto, habría que ver si existe algún prop de validar y cuando se valida

2021-01-20 12:03 UTC, faloi commented on src/components/login/Login.js
> +      if (values.dni === '' || values.contrasenia === '') {
Chusmeen esto, tiene buena pinta: https://www.npmjs.com/package/react-material-ui-form-validator

2021-01-24 16:17 UTC, JoaquinPettinari commented
![login](https://user-images.githubusercontent.com/48968618/105636108-65e20e00-5e45-11eb-9940-4fbdb506f4ca.gif)

Este es el Login. Está hecha la verificación de que no pueda acceder a rutas protegidas... después de logearse podría pero actualmente no, porque para acceder hay que hacerlo por url y el estado se perdería

![registro](https://user-images.githubusercontent.com/48968618/105636295-82327a80-5e46-11eb-98df-10881f996709.gif)

En el registro se guarda el token para después acceder a lo que haga falta

2021-01-25 17:18 UTC, faloi requested changes
Muy buen laburo. Dejé algunas sugerencias para que quede pipí-cucú, cualquier cosa la vemos por Discord.

2021-01-25 17:18 UTC, faloi commented on src/App.js
> +      {console.log(estaAutorizado)}
Borren esto.

2021-01-25 17:18 UTC, faloi commented on src/App.js
> +            <Route path="/login">
Insisto con que el login debería ser la ruta por defecto.

2021-01-25 17:18 UTC, faloi commented on src/App.js
> +  const [estaAutorizado, setEstaAutorizado] = useState(false);
Esto podría ir a un selector de Recoil, que mire si el usuario está seteado. De hecho cuando tengamos roles vamos a necesitar que devuelva qué rol tiene el usuario, así que el selector nos va a venir joya. Moviéndolo a un estado global, ya no hace falta pasárselo a cada componente que lo necesite usar.

2021-01-25 17:18 UTC, faloi commented on src/App.js
> +      }}
Un detalle pavo, se puede escribir sin llaves:

```suggestion
      render={() => isAuthenticated ? children : (<Redirect to={'/login'} />)}
```

2021-01-25 17:18 UTC, faloi commented on src/App.js
> +      }}
Ah, y el `=== true` es error de intro che. 😛

2021-01-25 17:18 UTC, faloi commented on src/components/espacios/AltaModificacionEspacio.js
> +      edificioId: 123,
Imagino que quedó de alguna prueba, volarlo.

2021-01-25 17:18 UTC, faloi commented on src/components/login/Login.js
> +    await sleep(3000);
¿Esto qué onda?

2021-01-25 17:18 UTC, faloi commented on src/components/login/Login.js
> +        });
¿Por qué no directamente guardar todo lo que viene de la API?

```suggestion
        setInfoUsuario(res);
```

2021-01-25 17:18 UTC, faloi commented on src/components/login/Login.js
> +          />
Debería ser un campo con `type=number`, sobre todo para que en el celu se vea el teclado numérico. En ese caso habría que cambiar la validación para usar `minNumber:1000000` y `maxNumber:99999999`, porque ya no va a ser un texto.

2021-01-25 17:18 UTC, faloi commented on src/components/login/Login.js
> +            errorMessages={['Este campo es requerido', ERRORES.dni]}
El mensajito de `Este campo es requerido` podría ir también a `ERRORES`, así no se repite en cada campo.

2021-01-25 17:18 UTC, faloi commented on src/components/registro/Registro.js
> +  const emailRegex = new RegExp('/S+@S+.S+/');
No hace falta esto, la biblioteca tiene una validación `isEmail`. Ver todas las que vienen en https://www.npmjs.com/package/react-form-validator-core.

2021-01-25 17:18 UTC, faloi commented on src/components/registro/Registro.js
> +    await sleep(3000);
De nuevo, esto definitivamente no está bien. Cuentenmé por qué lo pusieron y vemos cómo arreglarlo.

2021-01-25 17:18 UTC, faloi commented on src/components/registro/Registro.js
> +    }
No está mal, pero la biblioteca también soporta crear validadores propios, y se evitan tener que manejarlo por fuera.

En la documentación hay un ejemplo justo para este caso, que adaptado sería así:

```js
ValidatorForm.addValidationRule('isPasswordMatch', (value) => value === informacionDelUsuario.contrasenia));
```

2021-01-25 17:18 UTC, faloi commented on src/components/registro/Registro.js
> +              errorMessages={['Este campo es requerido', ERRORES.nombre]}
Lo mismo que les dije en la otra vista sobre el mensajito de campo requerido.

2021-01-25 17:18 UTC, faloi commented on src/components/registro/Registro.js
> +              errorMessages={['Este campo es requerido', ERRORES.nombre]}
Y ya que se va a usar en varias vistas, sería bueno moverlo a un archivo aparte así nos queda siempre el mismo mensaje.

2021-01-25 17:18 UTC, faloi commented on src/components/registro/Registro.js
> +              validators={['required', 'matchRegexp:^[0-9]{7,8}$']}
Lo mismo que en el login sobre validación y tipo del campo.

2021-01-25 17:18 UTC, faloi commented on src/components/registro/Registro.js
> +              validations={{ matchRegexp: emailRegex }}
Veo que más abajo usaron `isEmail`, esto debe haber quedado viejo entonces.

2021-01-25 17:18 UTC, faloi commented on src/components/registro/Registro.js
> +              validators={['required', 'minStringLength:6']}
Si toman mi sugerencia de más arriba, acá habría que agregar `isPasswordMatch`. Lo del length se podría sacar porque ya lo define el campo contraseña:

```suggestion
              validators={['required', 'isPasswordMatch']}
```

2021-01-25 17:18 UTC, faloi commented on src/components/registro/Registro.js
> +  contraseña: 'Ingrese una contraseña válida',
Aunque estemos en el 2021, esta ñ acá me da miedito... mejor vamos por el viejo y querido `contrasenia`.

2021-01-25 17:18 UTC, faloi commented on src/helpers/fetchApi.js
> +  return response;
¿Podrían hacer lo mismo en las demás funciones de este archivo? Así esto no nos vuelve a pasar en otro endpoint.

2021-01-25 17:18 UTC, faloi commented on src/state/login.js
> +  key: 'informacionUsuarioState',
No veníamos poniéndole sufijo `state` a las keys, sí al nombre de la const:

```suggestion
  key: 'informacionUsuario',
```

2021-01-25 17:18 UTC, faloi commented on src/state/login.js
> +  key: 'informacionUsuarioState',
Al margen de esto, le pondría directamente `usuario` como nombre, me parece redundante lo de `informacion`.

2021-01-25 17:19 UTC, faloi commented
> ![login](https://user-images.githubusercontent.com/48968618/105636108-65e20e00-5e45-11eb-9940-4fbdb506f4ca.gif)
> 
> Este es el Login. Está hecha la verificación de que no pueda acceder a rutas protegidas... después de logearse podría pero actualmente no, porque para acceder hay que hacerlo por url y el estado se perdería
> 
> ![registro](https://user-images.githubusercontent.com/48968618/105636295-82327a80-5e46-11eb-98df-10881f996709.gif)
> 
> En el registro se guarda el token para después acceder a lo que haga falta

¡Impecable! 😎 

Para la próxima ponelas directamente en la descripción (se puede editar) así no se pierde entre los comentarios.

2021-01-25 17:23 UTC, JoaquinPettinari commented on src/App.js
> +      }}
Te juro que el === true lo sacamos... habrá sido uno de esos Control + Z. No se quiso ir

2021-01-25 21:55 UTC, JoaquinPettinari commented on src/App.js
> +  const [estaAutorizado, setEstaAutorizado] = useState(false);
A un selector o un atomo?

2021-01-25 22:03 UTC, JoaquinPettinari commented on src/components/login/Login.js
> +    await sleep(3000);
Que cosa? El sleep? es para darle la "sensación" de que está cargando la página

2021-01-25 22:06 UTC, JoaquinPettinari commented on src/components/login/Login.js
> +        });
Para no guardar cosas de mas pero ahí está

2021-01-25 22:27 UTC, faloi commented on src/App.js
> +  const [estaAutorizado, setEstaAutorizado] = useState(false);
Selector que dependa del átomo usuario. O directamente pueden mirar si el átomo usuario tiene lo necesario, da igual.

2021-01-25 22:31 UTC, faloi commented on src/components/login/Login.js
> +    await sleep(3000);
Cuando esté interactuando con la API real va a tardar, no tiene sentido hacerle esperar más tiempo. 😂

2021-01-25 22:32 UTC, JoaquinPettinari commented on src/components/registro/Registro.js
> +              validations={{ matchRegexp: emailRegex }}
Estaba mas abajo, había 2 validatos

2021-01-25 22:33 UTC, JoaquinPettinari commented on src/components/login/Login.js
> +    await sleep(3000);
Bueno bueno, de momento lo dejamos para tener una buena experiencia de usuario jajaja

2021-01-25 23:46 UTC, JoaquinPettinari commented
Está listo para revisión, con todos los cambios pedidos

2021-01-26 01:18 UTC, faloi approved these changes

2021-01-26 01:18 UTC, merged