Pantalla de solicitud de autorización
unahur-covid/frontend pull request #13
Opened 2021-01-28 00:27 UTC by JoaquinPettinari

Closes unahur-covid/planificacion#28

2021-01-28 10:06 UTC, faloi requested changes
Laburaron de más, porque en la issue decía clarísimo que solo ibamos a preguntar si estuvo en contacto con otra persona. 

Ya que lo hicieron dejenló, pero acostumbrensé a leer en detalle (y varias veces) qué es lo que hay que hacer.

2021-01-28 10:06 UTC, faloi commented on package.json
> +    "moment": "^2.29.1",
Ya tenemos luxon que cumple la misma función, usen esa. Moment está deprecada.

2021-01-28 10:06 UTC, faloi commented on src/App.js
¿Para qué sería esta ruta?

2021-01-28 10:06 UTC, faloi commented on src/App.js
> +            <Route path="/inscripcion">
Si no estás logueado no te podés inscribir.

2021-01-28 10:06 UTC, faloi commented on src/components/actividadUsuario/FinalDDJJ.js
> +      {/*probando de poner colores*/}
Borrar comentario.

2021-01-28 10:06 UTC, faloi commented on src/components/actividadUsuario/FinalDDJJ.js
> +        <Button variant="contained" component={Link} to="/" color="primary">
Ojo que el inicio ahora es la pantalla de login. Mejor redirigir (por ahora) a la pantalla para pedir autorización. Si lo hacen con el selector que yo armé, ya nos queda para cuando la ruta dependa del rol.

2021-01-28 10:06 UTC, faloi commented on src/components/actividades/ListadoActividades.js
> +        'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOjEsImRuaSI6MTExMTIyMjIsImlhdCI6MTYxMTY5Njk2NSwiZXhwIjoxNjI3MjQ4OTY1fQ.eEttlDmeTCybNuQqTLXUum_FsmGC_QmEXdSQj3wCaIU',
¿Y esto para qué? El selector ya incluye el token del usuario logueado.

2021-01-28 10:06 UTC, faloi commented on src/components/inscripcionActividad/FinalDDJJ.js
> +  //borderColor:"#009688",
Borrar comentario.

2021-01-28 10:06 UTC, faloi commented on src/components/inscripcionActividad/FinalDDJJ.js
> +export default function FinalDDJJ() {
No entendí por qué hay dos componentes iguales. 🤔

2021-01-28 10:06 UTC, faloi commented on src/components/inscripcionActividad/Paso1DDJJ.js
> +  const matches = useMediaQuery('(min-width:600px)');
Me hace un poco de ruido que esto sea necesario, se supone que los componentes de material ya vienen preparados para ser responsive.

2021-01-28 10:06 UTC, faloi commented on src/components/inscripcionActividad/Paso1DDJJ.js
> +                const horaInicio = moment(actividad.fechaHoraInicio).format(
Usar luxon.

2021-01-28 10:06 UTC, faloi commented on src/state/usuario.js
> +  get: () => '/inscripcion',
Ojo, esto va a afectar también al admin. Hasta que no tengamos navegación basada en roles no hay mucho que hacer.

2021-01-28 10:06 UTC, faloi commented on src/App.js
> +            <Route path="/inscripcion">
Además, el concepto dentro de la app es solicitar autorización, sería bueno que la URL corresponda con eso.

2021-01-28 10:06 UTC, faloi commented on src/components/inscripcionActividad/InscripcionActividad.js
> +  const [numeroPaso, setNumeroPaso] = useState(1);
Está bueno lo que inventaron. Para la próxima, otra opción es usar un Stepper de Material https://material-ui.com/components/steppers/.

2021-01-28 10:06 UTC, faloi commented on src/components/inscripcionActividad/InscripcionActividad.js
> +    } catch (error) {
Este catch que no hace nada es peligroso, porque nos puede ocultar un error. Mejor no ponerlo y que si falla se rompa todo, así nos avivamos.

2021-01-28 10:06 UTC, faloi commented on src/components/inscripcionActividad/Paso1DDJJ.js
> +            <Autocomplete //NO SE NOS OCURRIÓ UNA FORMA MEJOR PARA ESTO
Bueno, la forma de hacerlo lindo era con `renderOption`, como el ejemplo de Google Maps que está en la web de Material.

2021-01-28 10:24 UTC, faloi commented on src/components/inscripcionActividad/FinalDDJJ.js
> +        <Grid mt={matches ? 10 : 4} display="flex" justifyContent="center">
Creo que la forma de cambiarle el tamaño sin el hook es esta:

```suggestion
        <Grid sm={10} xs={4} display="flex" justifyContent="center">
```

Los breakpoints los lista acá: https://material-ui.com/system/basics/#responsive

2021-01-29 13:38 UTC, faloi requested changes

2021-01-29 13:38 UTC, faloi commented on src/components/inscripcionActividad/InscripcionActividad.js
> +    } catch (error) {
Ahora está peor que antes, porque ni siquiera loguea. 😛 
Directamente saquen el try/catch.

2021-01-29 13:38 UTC, faloi commented on src/components/inscripcionActividad/Paso1DDJJ.js
> +                const day = capitalize(
Ya vimos por Discord que esto no es necesario, porque en español los días se deberían escribir en mayúsculas.

2021-01-29 13:38 UTC, faloi commented on src/components/inscripcionActividad/Paso3DDJJ.js
> +            {/* {moment(informacionSeleccionada.actividad.fechaHoraFin).format(
Acostumbrensé a mirar lo que suben antes de pedir review, ya van varios pull requests que los suben con cosas comentadas...

2021-01-29 13:38 UTC, faloi commented on src/components/inscripcionActividad/InscripcionActividad.js
> +      history.push('/solicitarAutorizacion/final');
En general no ponemos verbos en las rutas, sino nombres de recursos.
Esta podría llamarse `/autorizaciones/final` o `/autorizaciones/confirmacion` y la que es para solicitar `/autorizaciones/nueva` (así se llaman las que crean actividad y espacio).

2021-01-30 14:03 UTC, JoaquinPettinari commented
Estamos!!!

2021-01-30 19:43 UTC, faloi approved these changes

2021-01-30 19:44 UTC, merged