Navegación y home diferenciada por roles
unahur-covid/frontend pull request #19
Opened 2021-01-31 21:00 UTC by JoaquinPettinari

Closes unahur-covid/planificacion#40

![verificacionDeRol](https://user-images.githubusercontent.com/48968618/106397818-1a53d500-63ee-11eb-915f-6b192cb3f019.gif)

2021-02-01 15:04 UTC, faloi requested changes

2021-02-01 15:04 UTC, faloi commented on src/state/validacionRutaConRol.js
> +});
Movelo al `usuario.js`, así nos queda todo lo que tiene que ver con el usuario junto.

2021-02-01 15:04 UTC, faloi commented on src/components/autenticacion/PrivateRoute.js
> +import react from 'react';
Este `ìmport` creo que no hace falta.

2021-02-01 15:04 UTC, faloi commented on src/components/ui/NavBar.js
> +  const tieneRol = useRecoilValue(tieneRolState(['admin', 'bedel']));
La idea es que cada rol tenga en la navegación las páginas a las que puede ir. Por ahora eso sería:

* `admin`: listado de espacios y actividades (lo que hay ahora),
* `asistente`: nueva autorización,
* `bedel`: nada por ahora, cuando @CabreraTiago termine la pantalla de control estará eso.

Esto se puede lograr de varias maneras, en la issue puse una opción posible: tener un array con todas las rutas y filtrar según el rol actual. Otra sería tener un array por rol y ya, de todos modos no creo que se repitan las rutas entre roles.

En cualquier caso, el armado de ese array lo manejaría con un selector que dependa o del `usuario` o de `tieneRol`. Todo lo que tenga que ver con estado calculado conviene hacerlo con Recoil, que está optimizado para no recalcular cada vez que se renderiza un componente.

2021-02-01 15:05 UTC, faloi commented on src/components/ui/NavBar.js
> +  const tieneRol = useRecoilValue(tieneRolState(['admin', 'bedel']));
Una vez obtenido el array con los items de la navegación, la vista se armaría más o menos así:

```js
  items.map(({nombre, ruta}) =>
          <Button
            onClick={() => setScreenSelected(ruta)}
            className={classes.button}
            color="inherit"
            style={{
              backgroundColor: screenSelected.includes(ruta)
                ? '#009688'
                : '#4DB6AD',
            }}
            component={Link}
            to={ruta}
          >
            {nombre}
          </Button>
```

2021-02-01 15:08 UTC, JoaquinPettinari commented on src/components/ui/NavBar.js
> +  const tieneRol = useRecoilValue(tieneRolState(['admin', 'bedel']));
Es muy buena esta

2021-02-01 23:20 UTC, JoaquinPettinari commented
Listo!!

2021-02-01 23:48 UTC, JoaquinPettinari commented
Me aprobas esto?

2021-02-02 01:18 UTC, faloi approved these changes

2021-02-02 13:13 UTC, merged