Pantalla control de acceso
unahur-covid/frontend pull request #21
Opened 2021-02-01 20:36 UTC by CabreraTiago

Closes unahur-covid/planificacion#31

![Control de acceso](https://user-images.githubusercontent.com/48968913/106515060-dd521600-64b3-11eb-8a2b-beead3f49f87.gif)

2021-02-01 22:00 UTC, faloi requested changes
Muy bueno, solo dos pavadas para mejorar.

2021-02-01 22:00 UTC, faloi commented on src/state/actividades.js
> +});
Creo que sería mejor convertir al `todasLasActividades` en un `selectorFamily` que pueda recibir como argumento un objeto con `{ desde, hasta }`. Si lo tiene, lo incluye en el path y si no, no.

¿Qué te parece?

2021-02-01 22:00 UTC, faloi commented on src/state/autorizaciones.js
> +    return data;
Usá el selector `apiIndex` que hice yo, que ya tiene la cuestión del usuario resuelta.

2021-02-02 02:34 UTC, CabreraTiago commented on src/state/actividades.js
> +});
Entiendo, había intentado pasándole dos argumentos pero el segundo no me lo tomaba., evidentemente algo hice mal. Lo pruebo como indicas vos.

2021-02-02 12:52 UTC, faloi approved these changes
Si querés mergearlo como está, adelante. Pero si te queda algo de tiempo para dedicarle, van unas sugerencias.

2021-02-02 12:52 UTC, faloi commented on src/components/actividades/ControlAcceso.js
> +function SeleccionDeActividad({ actividades, setActividadSeleccionada }) {
Ya que hiciste el componente, sería bueno utilizarlo también en la vista de solicitud de autorización así nos queda unificado.

2021-02-02 12:52 UTC, faloi commented on src/state/actividades.js
> +};
Lo que podés hacer acá para evitarte el chequeo de `null` es ponerle un valor por default. Quedaría así:

```suggestion
const buildPath = ({ desde, hasta } = {}) => {
  const query = queryString.stringify(
    { desde, hasta },
    { skipNull: true }
  );
  return `actividades?${query}`;
};
```

Y luego donde lo uses y no quieras poner filtro, no haría falta pasar `null`.

2021-02-02 12:52 UTC, faloi commented on src/state/actividades.js
> +  get: (fecha) => async ({ get }) => {
Tal vez lo llamaría `filtro` en vez de `fecha`.

2021-02-02 12:52 UTC, faloi commented on src/state/actividades.js
> +import queryString from 'query-string';
Muy bueno este, no lo conocía. 👏🏽

2021-02-03 02:04 UTC, CabreraTiago commented on src/components/actividades/ControlAcceso.js
> +function SeleccionDeActividad({ actividades, setActividadSeleccionada }) {
Te lo voy a deber jaja, lo tengo en cuenta para unahur-covid/planificacion#53

2021-02-03 02:13 UTC, merged