Cerrar sesión / Borrar el navbar para el bedel, el footer y hacer que el logo redirija al inicio
unahur-covid/frontend pull request #26
Opened 2021-02-09 23:26 UTC by JoaquinPettinari

Closes unahur-covid/planificacion#64
Closes unahur-covid/planificacion#65
![headerResponsive](https://user-images.githubusercontent.com/48968618/107441974-fb9fbd80-6b14-11eb-888f-04eebd448030.gif)

Hay cosas que mejorar en la parte mobile, no está como flex row, está con grid  y posiciones.. por eso se va un poco de lugar a veces... faltaría mejorar diseño peeeero safa de momento, espero que les guste.

Espero feedbacks

2021-02-09 23:54 UTC, faloi requested changes

2021-02-09 23:54 UTC, faloi commented on src/App.js
> +//import Footer from './components/ui/Footer';
Eliminar comentario y componente footer.

2021-02-09 23:54 UTC, faloi commented on src/components/ui/PantallaDesktop.js
> +export default function PantallaDesktop({ hayUsuarioLogueado }) {
No le veo sentido a recibir esto por parámetro, se puede acceder al estado de Recoil directamente desde este componente.

2021-02-09 23:54 UTC, faloi commented on src/components/ui/PantallaMobile.js
> +  const { estadosPantalla, setEstadosPantalla, hayUsuarioLogueado } = props;
Mismo comentario que en el otro caso, lo de `hayUsuarioLogueado` se puede traer de Recoil.

2021-02-09 23:54 UTC, faloi commented on src/components/ui/PantallaMobile.js
> +        <Link to="/">
Debería ser link a la ruta inicial del rol, no a `/`. Tal vez tengas que volver a meter el selector que borraste, pero utilizando la función que ya definiste.

2021-02-09 23:54 UTC, faloi commented on src/components/ui/example.js
> +  {
Este archivo te quedó de prueba, volalo.

2021-02-09 23:54 UTC, faloi commented on src/state/usuario.js
> +    icono: <SportsIcon />,
No entiendo qué onda esto. 🤔 
Está bueno que el icono esté acá, pero me parece que al final no lo usaste.

2021-02-09 23:54 UTC, faloi commented on src/components/ui/BotonCerrarSesion.js
> +      </IconButton>
Solo mostraría este ícono cuando el usuario está logueado, me parece que no tiene sentido cuando aún no inició sesión, porque la única vista que puede ver es la de iniciar sesión. 😛

2021-02-09 23:54 UTC, faloi commented on src/components/ui/BotonCerrarSesion.js
> +        )}
Esto no tiene sentido si ocultás el icono del perfil cuando no está logueado.

2021-02-09 23:54 UTC, faloi commented on src/components/ui/BotonCerrarSesion.js
> +  const [anchorEl, setAnchorEl] = useState(null);
¿Qué significa `anchorEl`?

2021-02-09 23:54 UTC, faloi commented on src/components/ui/PantallaMobile.js
> +          </MenuItem>
Ah, y por favor sacá esto de Inicio, ya lo hablamos varias veces...

2021-02-09 23:55 UTC, JoaquinPettinari commented on src/state/usuario.js
> +    icono: <SportsIcon />,
Noo, eso quedó de prueba je, ahí lo saco

2021-02-09 23:56 UTC, JoaquinPettinari commented on src/components/ui/BotonCerrarSesion.js
> +        )}
El ícono no se oculta nunca, por eso cuando no estás logeado te dice "Iniciar sesión"

2021-02-09 23:59 UTC, faloi commented on src/components/ui/BotonCerrarSesion.js
> +        )}
Claro, pero mi sugerencia es ocultarlo.

2021-02-10 01:04 UTC, JoaquinPettinari commented on src/components/ui/BotonCerrarSesion.js
> +  const [anchorEl, setAnchorEl] = useState(null);
![image](https://user-images.githubusercontent.com/48968618/107449692-c9955800-6b22-11eb-9043-9e738586ad19.png)

2021-02-10 01:21 UTC, JoaquinPettinari commented
Listo

2021-02-10 13:08 UTC, faloi commented on src/components/ui/BotonCerrarSesion.js
> +  const [anchorEl, setAnchorEl] = useState(null);
`anchorElement`... qué les costaba poner un nombre digno... 🤦🏽

2021-02-10 13:33 UTC, faloi approved these changes

2021-02-10 13:39 UTC, merged