Selector carreras disponibles
unahur-covid/frontend pull request #28
Opened 2021-02-10 00:48 UTC by GerezPablo

Closes unahur-covid/planificacion#42

2021-02-10 13:50 UTC, faloi requested changes
Además del comentario, faltaría hacer esta parte:

> Además de eso, cambiar la pantalla de solicitud de autorización para que solo traiga aquellas que el asistente actual puede ver, utilizando el nuevo endpoint definido en #41.

Y por favor, incluí una captura de pantalla o GIF que muestre cómo quedó.

2021-02-10 13:50 UTC, faloi commented on src/components/actividades/AltaModificacionActividad.js
> +  const [carreraSeleccionada, setCarreraSeleccionada] = useState('');
Ojo que lo que tiene que llegar a la API es el campo `restriccionId`, con el id de la carrera seleccionada.

2021-02-14 17:35 UTC, GerezPablo commented
Actividades disponibles para un estudiante que esta cursando una carrera determinada
![image](https://user-images.githubusercontent.com/48962929/107884028-49c80e80-6ed1-11eb-8ee1-d9a183a4c44d.png)

Carrera para una actividad 
![image](https://user-images.githubusercontent.com/48962929/107884100-9f042000-6ed1-11eb-951e-9b54a2fb580e.png)

![image](https://user-images.githubusercontent.com/48962929/107884128-c955dd80-6ed1-11eb-81fe-2d7bc8009938.png)

2021-02-15 01:32 UTC, faloi requested changes

2021-02-15 01:32 UTC, faloi commented on src/components/actividades/AltaModificacionActividad.js
> +              <InputLabel id="labelCarreras">Elija una carrera</InputLabel>
Dijimos que ibamos a usar voseo. Además, podría pasar que la actividad sea pública y en ese caso este campo quedaría vacío.

Tal vez podría `Solo para carrera` y en el input algo como `Elegí una carrera o dejalo en blanco`. Después podemos mejorar los textos pero creo que dan una idea...

2021-02-15 01:32 UTC, faloi commented on src/components/actividades/AltaModificacionActividad.js
> +              <Select
Son demasiadas opciones para usar un select, lo haría sí o sí con Autocomplete.

2021-02-15 01:32 UTC, faloi commented on src/components/inscripcionAutorizacion/Paso1DDJJ.js
> +    actividadesUsuario({ desde: fechaActual, hasta: fechaActual })
Solo habría que setear el `desde`, porque te tiene que permitir anotarte a actividades futuras (pero no pasadas). Así como está solo podés anotarte a las que sean hoy.

2021-02-15 01:32 UTC, faloi commented on src/utils/queryUtils.js
> +export const buildPath = (path, { desde, hasta } = {}) => {
Muy bueno este...👏
A futuro, estaría bueno que directamente el `apiIndex` pueda recibir como segundo parámetro los argumentos del query string y hacer esto.

2021-02-15 02:55 UTC, faloi commented on src/components/inscripcionAutorizacion/Paso1DDJJ.js
> +    actividadesUsuario({ desde: fechaActual, hasta: fechaActual })
Ojo que esto va a dar conflictos con la issue de unificar el selector, hablen entre ustedes. 

Además de eso, estaría bueno que la API devuelva las actividades ordenadas por fecha ascendente (primero las más cercanas). No hace falta que lo hagas, pero si podés cargate una issue.

2021-02-17 16:10 UTC, faloi approved these changes

2021-02-17 23:05 UTC, merged