Los selectores no muestran las actividades inactivas
unahur-covid/frontend pull request #36
Opened 2021-02-20 19:08 UTC by CabreraTiago

## :dart: Objetivo

Closes unahur-covid/planificacion#63

## :camera_flash: Capturas de pantalla / GIFs

![actividades_inactivas](https://user-images.githubusercontent.com/48968913/108605874-9d38d180-7395-11eb-8319-b0facdbad98d.gif)

2021-02-22 16:49 UTC, faloi requested changes
Groso, te comenté una pavada para que ya quede más prolijo.

Sé que no era parte de la issue, pero si podés agregale una columna que muestre si está activa, igual que como está en Espacios. Si no, medio que se hace difícil para el admin usar esta funcionalidad.

2021-02-22 16:49 UTC, faloi commented on src/utils/queryUtils.js
> +export const buildPath = (path, { desde, hasta, inactivas } = {}) => {
Esto podrías hacerlo más genérico. Que el segundo parámetro sea el querystring en formato objeto, no importa con qué atributos venga. Eso se lo pasás al `stringify` y va a hacer su magia. 

Ahora lo estás desarmando y volviendo a armar más abajo, no tiene mucho sentido.

2021-02-22 16:49 UTC, faloi commented on src/utils/queryUtils.js
> +export const buildPath = (path, { desde, hasta, inactivas } = {}) => {
Igual, muy bueno el cambio. 👏🏽

2021-02-23 03:59 UTC, CabreraTiago commented
![image](https://user-images.githubusercontent.com/48968913/108800594-56540300-7572-11eb-9c25-58f93d6912fb.png)

2021-02-23 11:29 UTC, faloi approved these changes

2021-02-23 11:29 UTC, faloi commented on src/components/actividades/ListadoActividades.js
> +                      <FiberManualRecordIcon className={classes.activa} />
Perfecto, solo otra forma de hacerlo:


```suggestion
                      <FiberManualRecordIcon className={actividad.activa ? classes.activa : classes.inactiva} />
```

2021-02-23 11:29 UTC, faloi commented on src/components/actividades/ListadoActividades.js
> +                      <FiberManualRecordIcon className={classes.activa} />
:clap: por deshardcodear los colores.

2021-02-23 11:30 UTC, merged