Asistente: pantalla para ver actividades / Asistente: permitir cancelar una autorización
unahur-covid/frontend pull request #37
Opened 2021-02-20 21:54 UTC by JoaquinPettinari

Closes unahur-covid/planificacion#62
Closes unahur-covid/planificacion#73

![misActividades](https://user-images.githubusercontent.com/48968618/108609483-f19b7b80-73ac-11eb-8b1b-4db3ad0a7bfc.gif)

2021-02-22 17:00 UTC, faloi requested changes

2021-02-22 17:00 UTC, faloi commented on src/App.js
> +        rolesPermitidos={['asistente', 'admin']}
No tiene sentido esta pantalla para el admin.

```suggestion
        rolesPermitidos={['asistente']}
```

2021-02-22 17:00 UTC, faloi commented on src/App.js
> +import MisActividades from './components/misActividades/MisActividades';
Movela a la carpeta `actividades`, así queda todo concentrado ahí.

2021-02-22 17:00 UTC, faloi commented on src/state/usuario.js
> +
Sería más bien `autorizacionesUsuario` o algo así. El todas da la sensación de que trae todas las que existen.

2021-02-22 17:00 UTC, faloi commented on src/state/usuario.js
> +      return '/misActividades';
No se usa camelCase para las rutas. Podés ponerle `/autorizaciones`, para ser consistentes con `/autorizaciones/nueva`. O mejor aún, ponele directamente `/turnos` así no hay que volver a cambiarlo más adelante.

2021-02-22 17:00 UTC, faloi commented on src/state/usuario.js
> +    ruta: '/misActividades',
```suggestion
    nombre: 'Mis turnos',
    ruta: '/turnos',
```

2021-02-22 17:00 UTC, faloi commented on src/components/ui/Tarjeta.js
> +    // backgroundColor: palette.error.main,
```suggestion
```

2021-02-22 17:00 UTC, faloi commented on src/components/ui/Tarjeta.js
> +      nombre: entidad.Actividad.nombre,
Jeje, buen hack, me gusta.

2021-02-22 17:00 UTC, faloi commented on src/components/ui/Tarjeta.js
> +export default function Tarjeta(props) {
¿`Tarjeta` de qué? Ponele `TarjetaTurno` o algo más representativo.

2021-02-22 17:00 UTC, faloi commented on src/components/ui/BotonCerrarSesion.js
> +        </Avatar>
Hubo empate en Discord, podemos probarlo a ver qué onda. Pero el `backgroundColor` movelo al `useStyles` y usá algún color del tema. No hardcodeemos más colores por todos lados.

2021-02-22 17:00 UTC, faloi commented on src/components/ui/Acordion.js
> +export default function Acordion(props) {
De nuevo, ¿`Acordion` de qué?

2021-02-22 17:00 UTC, faloi commented on src/components/misActividades/MisActividades.js
> +            </Grid>
Me gusta la idea de mostrar un mensajito cuando aún no hay turnos, pero en el GIF que subiste se ve medio feo, como desplazado a la izquierda. Fijate si podés acomodarlo.

2021-02-22 22:40 UTC, JoaquinPettinari commented
Listo para la review

2021-02-23 11:49 UTC, faloi approved these changes

2021-02-23 11:49 UTC, faloi commented on src/components/actividades/MisActividades.js
> +            <Button
Para la próxima, podés crearte un componente acá nomás, que sea ponele BotonNuevoTurno. En el constructor le mandas un props genérico y luego lo aplicás con ...props, eso te permitiría por ejemplo ponerle el fullWidth.

2021-02-23 11:49 UTC, merged