El campo DNI tiene flechas up/dwn
unahur-covid/frontend pull request #39
Opened 2021-02-20 23:18 UTC by JoaquinPettinari

Closes unahur-covid/planificacion#83

![removeArrows](https://user-images.githubusercontent.com/48968618/108610958-b7d07200-73b8-11eb-8bf9-926dbb1a3cd7.gif)

2021-02-22 16:34 UTC, faloi requested changes

2021-02-22 16:34 UTC, faloi commented on src/components/espacios/AltaModificacionEspacio.js
> +            className={classes.numberTextField}
En este campo sí dejaría la flecha, puede llegar a ser útil.

2021-02-22 16:34 UTC, faloi commented on src/components/login/Login.js
> +});
Si lo vas a usar en varios lugares, llevalo a un helper para no repetir. Y ponele algún nombre más representativo, como `numberFieldWithoutArrows`.

2021-02-22 16:34 UTC, faloi commented on src/components/login/Login.js
> +});
Lo haría así:

```js
// En algún archivo de helpers:
export const useInputStyles = makeStyles({
  numberFieldWithoutArrows: {
    minWidth: 250,
    '& input::-webkit-clear-button, & input::-webkit-outer-spin-button, & input::-webkit-inner-spin-button': {
      display: 'none',
    },
  },
});

// Donde lo vayas a usar

import { useInputStyles } from 'mihelper';

const inputClasses = useInputStyles();

<TextValidator
  className={inputClasses.numberFieldWithoutArrows}
```

2021-02-22 16:34 UTC, faloi commented on src/components/login/Login.js
> +});
Y agregale lo necesario para que tampoco se vea en Firefox porfa.

2021-02-23 11:55 UTC, faloi requested changes
Fijate que tenés conflictos también.

2021-02-23 11:55 UTC, faloi commented on src/components/actividades/AltaModificacionActividad.js
> +  numberTextField: {
Entiendo que esto te quedó de más acá.

2021-02-23 11:55 UTC, faloi commented on src/utils/numberFieldWithoutArrows.js
> +    '& input::-webkit-clear-button, & input::-webkit-outer-spin-button, & input::-webkit-inner-spin-button': {
No veo que hayas agregado lo de Firefox.  🤔

2021-02-23 22:16 UTC, JoaquinPettinari commented
Listo para mergear este también

2021-02-23 22:23 UTC, merged