Listado de espacios
unahur-covid/frontend pull request #4
Opened 2021-01-05 02:51 UTC by JoaquinPettinari

Habría que acomodar la tabla mas centrada y ver el estilo de la modal

2021-01-05 11:47 UTC, faloi commented
¿Podrían sumar algunas capturas para ver cómo quedó?

2021-01-05 11:49 UTC, JoaquinPettinari commented
> ¿Podrían sumar algunas capturas para ver cómo quedó?

Yo ahora no puedo, mas tarde si. Capaz alguna de las chicas puede

2021-01-05 11:58 UTC, faloi requested changes

2021-01-05 11:58 UTC, faloi commented on package.json
> +    "material-ui-image": "^3.3.1",
Me parece que al final no lo usaron, en ese caso borrenlo y actualicen el lock también.

2021-01-05 11:58 UTC, faloi commented on src/App.js
>                <DatosUsuario />
La ruta de usuarios era solo para probar, ya se puede borrar al igual que los componentes que no sirvsn.

2021-01-05 11:58 UTC, faloi commented on src/components/Header.js
> +// import Typography from '@material-ui/core/Typography';
No dejen código comentado. Hay por varios lados más.

2021-01-05 11:58 UTC, faloi commented on src/components/Tabla.js
> +const rows = {
Por más que la API no estuviera lista, esto lo tendrían que haber puesto en un selector de Recoil, que luego se puede reemplazar con la implementación posta.

2021-01-05 11:58 UTC, faloi commented on src/components/VentanaModal.js
> +  const eliminarEspacio = () => {
Tiene que hacer un llamado a la API para borrar el espacio.

2021-01-05 11:58 UTC, faloi commented on src/components/PantallaLogin.js
> +      <Tabla />
Este componente se podría definir acá mismo, ya que no se va a usar en otro lado. Y si va a otro archivo, habría que ponerle un mejor nombre (Tabla es demasiado genérico).

2021-01-05 11:58 UTC, faloi commented on src/components/PantallaLogin.js
> +      <Header />
Tal vez pueda ir más arriba, ya que lo vamos a querer en todas las oantallas.

2021-01-05 11:58 UTC, faloi commented on src/components/Header.js
> +  // Note that you normally won't need to set the window ref as useScrollTrigger
Denle bola a este comentario. 😛

2021-01-05 11:58 UTC, faloi commented on src/components/Header.js
> +   * You won't need it on your project.
Y a este también.

2021-01-05 23:37 UTC, JoaquinPettinari commented on src/components/Tabla.js
> +const rows = {
No entendemos el recoil, por eso lo hardcodeamos

2021-01-06 00:45 UTC, JoaquinPettinari commented
Ya hicimos los cambios, esta listo para revisar

2021-01-06 12:05 UTC, faloi reviewed
Mergeamos así, pero atenti a los comentarios nuevos para la próxima issue.

2021-01-06 12:05 UTC, faloi commented on src/components/Header.js
> +          {/* <IconButton
Acá quedó código comentado.

2021-01-06 12:05 UTC, faloi commented on src/components/VentanaModal.js
> +      });
Para cerrar esta issue lo podemos dejar así, pero sería bueno:
* mover esto a otro lado, no está bueno que el llamado a la API esté codeado en el botón. Por ejemplo un objeto/clase API que tenga los métodos para interactuar,
* usar `async/await` en vez de promises.

2021-01-06 12:05 UTC, faloi commented on src/state/espacios.js
> +  const response = await fetch(`${apiUrl}/${path}`);
Si metieron axios, sería bueno usarlo en todos lados.

2021-01-06 12:05 UTC, faloi commented
Ah, y al borrar lo de usuarios se rompió el test que habia. Borrenló (o arreglenlo) para que no rompa el build.

2021-01-06 12:05 UTC, merged

2021-01-06 13:41 UTC, JoaquinPettinari commented on src/components/VentanaModal.js
> +      });
Lo de hacer una nueva carpeta con las llamadas a apis lo ibamos a proponer hoy, nos pareció dejarlo así de momento, porque estabamos en duda si andaba o no

2021-01-06 22:25 UTC, faloi commented
Closes #1