Mostrar cupos disponibles en listado actividades
unahur-covid/frontend pull request #40
Opened 2021-02-21 01:27 UTC by JoaquinPettinari

Closes unahur-covid/planificacion#86

![image](https://user-images.githubusercontent.com/48968618/108612810-be67e500-73ca-11eb-85c0-2c4b7a7583a9.png)

2021-02-22 16:40 UTC, faloi requested changes

2021-02-22 16:40 UTC, faloi commented on src/components/actividades/ListadoActividades.js
> +      // </Typography>
Borrar esto.

```suggestion
```

2021-02-22 16:40 UTC, faloi commented on src/components/actividades/ListadoActividades.js
> +    }
No está bueno hacerlo así, usá los colores del theme de material. 
Tendrías que crear tres clases en el `useStyles` y acá en el if decidir cuál le ponés al Chip. Si no sale avisame y te doy una mano.

2021-02-22 16:40 UTC, faloi commented on src/components/actividades/ListadoActividades.js
> +                <TableCell>Fecha/Hora Inicio-Fin</TableCell>
```suggestion
                <TableCell>Fecha y hora</TableCell>
```

2021-02-22 16:40 UTC, faloi commented on src/components/actividades/ListadoActividades.js
> +                <TableCell>Cupos</TableCell>
```suggestion
                <TableCell>Cupo</TableCell>
```

2021-02-22 16:40 UTC, faloi commented on src/components/actividades/ListadoActividades.js
> +  const cuposConSuColor = (anotados, cantidadMax) => {
El nombre de los componentes va en mayúscula, y lo de `conSuColor` es redundante.

```suggestion
  const Cupo = (anotados, cantidadMax) => {
```

2021-02-22 16:40 UTC, faloi commented on src/components/actividades/ListadoActividades.js
> +        style={{ backgroundColor: background, color: textColor }}
En vez de esto, debería ir `className`, con la clase que elegiste según lo que te puse más arriba.

2021-02-22 16:41 UTC, faloi commented on src/components/actividades/ListadoActividades.js
> +  const cuposConSuColor = (anotados, cantidadMax) => {
Para convertirlo en un componente, deberías hacer que reciba props, y no dos parámetros.

2021-02-23 00:54 UTC, JoaquinPettinari commented
Estamos

2021-02-23 11:44 UTC, faloi approved these changes
Tenés que solucionar los conflictos y mergeamos.

2021-02-23 11:44 UTC, faloi commented on src/components/actividades/ListadoActividades.js
> +  succsess: {
```suggestion
  success: {
```

2021-02-23 11:44 UTC, faloi commented on src/components/actividades/ListadoActividades.js
> +        [classes.succsess]: porcentaje < 30,
```suggestion
        [classes.success]: porcentaje < 30,
```

2021-02-23 21:46 UTC, merged