Se sacaron datos de la DDJJ y se agregó una advertencia
unahur-covid/frontend pull request #41
Opened 2021-02-21 22:29 UTC by GerezPablo

## :dart: Objetivo
Borrar campos de laDDJJ innecesarios.

Closes unahur-covid/planificacion#91

## :camera_flash: Capturas de pantalla / GIFs
![image](https://user-images.githubusercontent.com/48962929/108640892-0b0af900-747b-11eb-84ec-e2f3eb94cd5a.png)
![image](https://user-images.githubusercontent.com/48962929/108640897-12320700-747b-11eb-8300-dc545ee5b874.png)

2021-02-21 23:08 UTC, faloi requested changes
Además de esas dos pavadas, acordate que hay que modificar el back para que guarde esta info.

2021-02-21 23:08 UTC, faloi commented on src/components/inscripcionAutorizacion/Paso2DDJJ.js
> +      {console.log(informacionSeleccionada)}
Borrar esto.

2021-02-21 23:08 UTC, faloi commented on src/components/inscripcionAutorizacion/InscripcionActividad.js
> +  capacitacionUNAHUR: 'false',
Debería ser booleano, no string.

2021-02-21 23:10 UTC, faloi commented on src/components/inscripcionAutorizacion/InscripcionActividad.js
> +  capacitacionUNAHUR: 'false',
Una más: ya que vas a tener que modificar el back, cambiale el nombre a `completoCapacitacion`. Por ahora iría como atributo de la autorización.

2021-02-21 23:25 UTC, GerezPablo commented on src/components/inscripcionAutorizacion/InscripcionActividad.js
> +  capacitacionUNAHUR: 'false',
Ya hice el cambio en el back, lo subí al mismo tiempo. Armé el PR y todo

2021-02-21 23:28 UTC, faloi commented on src/components/inscripcionAutorizacion/InscripcionActividad.js
> +  capacitacionUNAHUR: 'false',
Groso, no lo vi. Cambiale el nombre y mergeamos.

2021-02-23 12:31 UTC, faloi approved these changes

2021-02-23 12:31 UTC, merged