Mejoras ux mas issues
unahur-covid/frontend pull request #43
Opened 2021-02-24 04:51 UTC by JoaquinPettinari

Closes unahur-covid/planificacion#85
Closes unahur-covid/planificacion#88
Closes unahur-covid/planificacion#94

Además de los label, arreglé que cuando creas/editas una actividad/espacio, se siga mostrando en oscuro el botó del navegador (arriba)
![Selección_008](https://user-images.githubusercontent.com/48968618/108949140-9f738800-7642-11eb-8c29-d50dd5476354.png)
![Selección_006](https://user-images.githubusercontent.com/48968618/108949137-9edaf180-7642-11eb-99d8-2ba087c49c83.png)

![Selección_009](https://user-images.githubusercontent.com/48968618/108949141-a00c1e80-7642-11eb-9c16-80b89a811c86.png)
![Selección_010](https://user-images.githubusercontent.com/48968618/108949142-a00c1e80-7642-11eb-9ec9-27f138b96c1a.png)
![Selección_011](https://user-images.githubusercontent.com/48968618/108949145-a0a4b500-7642-11eb-995b-4b8bdd5f5a38.png)
![Selección_012](https://user-images.githubusercontent.com/48968618/108949146-a13d4b80-7642-11eb-8e22-3cfc8e44648e.png)

2021-02-24 12:48 UTC, faloi requested changes
Quedaron muy buenos los formularios, mucho más limpios que antes.

2021-02-24 12:48 UTC, faloi commented on src/components/actividades/AltaModificacionActividad.js
> +                label="Responsable"
Le pondría `Persona responsable` para que quede claro a qué nos referimos.

2021-02-24 12:48 UTC, faloi commented on src/components/actividades/AltaModificacionActividad.js
> +                validators={['minNumber:100000']}
No validaría nada acá, que pongan lo que quieran.

2021-02-24 12:48 UTC, faloi commented on src/components/actividades/AltaModificacionActividad.js
> +            <FormLabel component="legend">Estado:</FormLabel>
Este lo pondría abajo de todo el form, se ve medio feo ahí en el medio, como que rompe la continuidad.

2021-02-24 12:48 UTC, faloi commented on src/components/espacios/AltaModificacionEspacio.js
> +    '& input::-webkit-clear-button, & input::-webkit-outer-spin-button, & input::-webkit-inner-spin-button': {
¿Volvió esto? Si ya habías hecho el hook compartido...

2021-02-24 12:48 UTC, faloi commented on src/components/login/Login.js
> +              label="Ingresá una contraseña"
```suggestion
              label="Ingresá tu contraseña"
```

2021-02-24 12:48 UTC, faloi commented on src/components/registro/Registro.js
> +                label="Ingresá tu nombre/s"
```suggestion
                label="Ingresá tu/s nombre/s"
```

2021-02-24 12:48 UTC, faloi commented on src/components/registro/Registro.js
> +                label="Ingresá tu apellido/s"
```suggestion
                label="Ingresá tu/s apellido/s"
```

2021-02-24 12:48 UTC, faloi commented on src/components/registro/Registro.js
> +                label="Confirme la contraseña"
```suggestion
                label="Repetí tu contraseña"
```

2021-02-24 12:48 UTC, faloi commented on src/components/ui/NavBar.js
> +              [classes.linkActivo]: location.pathname.includes(ruta),
Me gusta este truco. 👌

2021-02-24 12:48 UTC, faloi commented on src/components/ui/PantallaMobile.js
> +          key={id}
Bien por sacar este warning molesto jaja.

2021-02-24 12:48 UTC, faloi commented on src/components/ui/PantallaMobile.js
> +          key={id}
También le podrías haber puesto el nombre, no se va a repetir.

2021-02-24 12:48 UTC, faloi commented on src/components/actividades/AltaModificacionActividad.js
> +  const carreraSeleccionada = find(propEq('id', restriccionId))(carreras);
Me gusta que le vayan agarrando gustito a Ramda. La lista también se puede pasar como segundo parámetro, tal vez más limpio porque usás menos paréntesis:


```suggestion
  const carreraSeleccionada = find(propEq('id', restriccionId), carreras);
```

2021-02-24 22:58 UTC, JoaquinPettinari commented
Listo

2021-02-25 00:00 UTC, faloi approved these changes

2021-02-25 00:00 UTC, merged