UI - Búsqueda por nombre de actividad o espacio en listado de actividades y usuarios en control de turnos
unahur-covid/frontend pull request #54
Opened 2021-02-27 04:12 UTC by JoaquinPettinari

## :dart: Objetivo

Closes unahur-covid/planificacion#103
Closes unahur-covid/planificacion#78

## :memo: Comentarios adicionales

Espero que te guste jajaj

## :camera_flash: Capturas de pantalla / GIFs

Buscador en Actividades/Espacios

![buscadorActividadEspacio](https://user-images.githubusercontent.com/48968618/109375073-a1368900-7898-11eb-80ea-16314bd90118.gif)

Buscador en Bedel. Aclaración. Este busca por nombre, apellido o dni (goooood)

![buscadorBedel](https://user-images.githubusercontent.com/48968618/109375079-b27f9580-7898-11eb-86b4-0d605f463510.gif)

2021-02-27 14:26 UTC, faloi requested changes
Estéticamente quedó bien, aunque en la pantalla del bedel ya lo centrado me hace un poco de ruido. Tiraría todo a la izquierda.

2021-02-27 14:26 UTC, faloi commented on src/components/ui/BuscadorDePersonas.js
> +    <TextField
_Creo_ que si le ponés `type="search"` te agrega una cruz para borrar el contenido.

2021-02-27 14:26 UTC, faloi commented on src/components/ui/BuscadorDePersonas.js
> +    const nuevaLista = filter((it) => validar(it), listaDeRecoil);
No hace falta crear una función inline, validar ya es una función:

```suggestion
    const nuevaLista = filter(validar, listaDeRecoil);
```

2021-02-27 14:26 UTC, faloi commented on src/components/ui/BuscadorDePersonas.js
> +    const validarBusqueda = (valor) => {
Todas estas funciones definilas fuera del `filtrarLista`, así como está se vuelven a crear a cada rato.

2021-02-27 14:26 UTC, faloi commented on src/utils/parserStringToLowerCase.js
> +export const parserStringToLowerCase = (string) => {
Un parser es algo que transforma un string en otra cosa con más semántica, por ejemplo extrae dominio y nombre de una dirección de mail. Esto no es un parser. Lo llamaría `toLowerWithoutDiacritics` o `minusculasSinTildes`.

2021-02-27 14:26 UTC, faloi commented on src/components/actividades/ListadoActividades.js
> +  const [actividades, setActividades] = useState(actividadesRecoil);
Este y el otro estado los vas a tener que sacar, porque cuando se actualicen las actividades no van a cambiar.

2021-02-27 14:26 UTC, faloi commented on src/components/actividades/ListadoActividades.js
> +            label={'Buscá una actividad'}
Acá también se pedía poder buscar por nombre del espacio.

2021-02-28 16:12 UTC, JoaquinPettinari commented
Estaaaamooos

2021-02-28 16:49 UTC, faloi approved these changes

2021-02-28 16:53 UTC, merged