Actividades futuras: filtro para la hora
unahur-covid/frontend pull request #69
Opened 2021-03-17 01:05 UTC by AyelenRdgz

Closes unahur-turnos/planificacion#102

## :memo: 
Se modifica el filtro para que tome en cuenta la hora al mostrar las actividades.

## :camera_flash: 
![image](https://user-images.githubusercontent.com/42378578/111399216-a91d6800-86a3-11eb-8336-3b06ab552d8a.png)

2021-03-22 19:12 UTC, faloi requested changes

2021-03-22 19:12 UTC, faloi commented on src/components/inscripcionTurnos/Paso1DDJJ.js
> +  };
Si bien resuelve el problema, en la issue se pedía que lo que se modifique es el llamado a la API, no hacer un filtro en memoria. ¿Probaron eso?

Habría que cambiar el llamado a `actividadesUsuario` que está en la línea 22.

2021-03-22 19:12 UTC, faloi commented on src/components/inscripcionTurnos/Paso1DDJJ.js
> +import { formatISO } from '../../utils/dateUtils';
Si esto no se va a usar, sacarlo.

2021-03-24 02:55 UTC, AyelenRdgz commented on src/components/inscripcionTurnos/Paso1DDJJ.js
> +  };
Fede, sacamos el filtro dentro de actividades usuario porque nos dimos cuenta que en el back ya solo hace el 'desde' con la fecha actual. Ahora, esta issue es del front, no comprendemos como hacerlo de otra manera desde acá, sino, modificar en el back la funcion 'getFiltroFecha' para que filtre por hora también.

2021-03-25 22:45 UTC, faloi commented on src/components/inscripcionTurnos/Paso1DDJJ.js
> +  const actividades = useRecoilValue(actividadesUsuario());
Mi sugerencia es probar esto:

```suggestion
  const actividades = useRecoilValue(actividadesUsuario({ desde: fechaActual }));
```

2021-03-26 15:55 UTC, faloi approved these changes

2021-03-26 15:55 UTC, merged