Bedel puede descargar archivo csv.
unahur-covid/frontend pull request #73
Opened 2021-05-19 00:59 UTC by FlorenciaMssy

Los bedeles pueden descargar un archivo en formato csv que contiene los datos de las personas que están habilitadas para ingresar a cierta actividad.

## :camera_flash: 
![csv](https://user-images.githubusercontent.com/48962884/118741212-255b3580-b824-11eb-951b-c1f06feef689.png)

2021-05-20 12:26 UTC, JoaquinPettinari approved these changes
Está buenisimo !! 👏👏👏👏👏

2021-05-20 12:26 UTC, JoaquinPettinari commented on src/components/actividades/ControlAcceso.js
> +          </Button>
Probaron como queda el ícono?

2021-05-20 12:26 UTC, JoaquinPettinari commented on src/components/actividades/ControlAcceso.js
> +import { dateFormatter, toString } from '../../utils/dateUtils';
Este que no está usado hay que borrarlo

2021-06-05 20:47 UTC, CabreraTiago commented
Vean si se puede cambiar el nombre del archivo descargado. `generatedBy_react-csv` no es muy descriptivo.

2021-06-05 20:55 UTC, CabreraTiago requested changes

2021-06-05 20:55 UTC, CabreraTiago commented on src/components/actividades/ControlAcceso.js
> +          </Button>
La ubicación del botón no es la ideal (podría ser debajo del listado de asistentes), incluso sale con un subrayado azul.

![image](https://user-images.githubusercontent.com/48968913/120905219-f2d47980-c626-11eb-90b8-bc257709e50b.png)

Agregar una descripción más acorde a lo que se está descargando.

2021-07-08 21:12 UTC, JoaquinPettinari approved these changes

2021-07-10 18:27 UTC, CabreraTiago requested changes

2021-07-10 18:27 UTC, CabreraTiago commented on src/components/actividades/ControlAcceso.js
> +          </Tooltip>
Me refería a algo de este estilo:

![image](https://user-images.githubusercontent.com/48968913/125172963-e47ffd00-e192-11eb-901f-2294ce66d49b.png)

Que aparezca justo debajo del listado. Para sacarle la línea azul que aparece en el botón pueden agregar lo siguiente en la etiqueta `CSVLink`: `style={{ textDecoration: 'none' }}`

2021-07-12 22:00 UTC, AyelenRdgz commented on src/components/actividades/ControlAcceso.js
> +          </Tooltip>
Queda como lo pusimos porque con Flor no estamos de acuerdo de que quede mejor de esa forma, perdón Tiaguin :(

2021-07-12 22:05 UTC, CabreraTiago approved these changes

2021-07-12 22:05 UTC, merged